//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private float fОклад;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Название CustomAttributes)

        // *** End programmer edit section *** (Должности.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Название Get start)

                // *** End programmer edit section *** (Должности.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Должности.Название Get end)

                // *** End programmer edit section *** (Должности.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Название Set start)

                // *** End programmer edit section *** (Должности.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Должности.Название Set end)

                // *** End programmer edit section *** (Должности.Название Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Оклад CustomAttributes)

        // *** End programmer edit section *** (Должности.Оклад CustomAttributes)
        [NotNull()]
        public virtual float Оклад
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Оклад Get start)

                // *** End programmer edit section *** (Должности.Оклад Get start)
                float result = this.fОклад;
                // *** Start programmer edit section *** (Должности.Оклад Get end)

                // *** End programmer edit section *** (Должности.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Оклад Set start)

                // *** End programmer edit section *** (Должности.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (Должности.Оклад Set end)

                // *** End programmer edit section *** (Должности.Оклад Set end)
            }
        }
    }
}
