//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЛКС.
    /// </summary>
    // *** Start programmer edit section *** (ЛКС CustomAttributes)

    // *** End programmer edit section *** (ЛКС CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЛКС : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fДолжность;
        
        private string fОтдел;
        
        private string fКонтакты;
        
        private string fОбразование;
        
        private System.DateTime fДата_приема;
        
        // *** Start programmer edit section *** (ЛКС CustomMembers)

        // *** End programmer edit section *** (ЛКС CustomMembers)

        
        /// <summary>
        /// Дата_приема.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.Дата_приема CustomAttributes)

        // *** End programmer edit section *** (ЛКС.Дата_приема CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата_приема
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.Дата_приема Get start)

                // *** End programmer edit section *** (ЛКС.Дата_приема Get start)
                System.DateTime result = this.fДата_приема;
                // *** Start programmer edit section *** (ЛКС.Дата_приема Get end)

                // *** End programmer edit section *** (ЛКС.Дата_приема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.Дата_приема Set start)

                // *** End programmer edit section *** (ЛКС.Дата_приема Set start)
                this.fДата_приема = value;
                // *** Start programmer edit section *** (ЛКС.Дата_приема Set end)

                // *** End programmer edit section *** (ЛКС.Дата_приема Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.Должность CustomAttributes)

        // *** End programmer edit section *** (ЛКС.Должность CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.Должность Get start)

                // *** End programmer edit section *** (ЛКС.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ЛКС.Должность Get end)

                // *** End programmer edit section *** (ЛКС.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.Должность Set start)

                // *** End programmer edit section *** (ЛКС.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ЛКС.Должность Set end)

                // *** End programmer edit section *** (ЛКС.Должность Set end)
            }
        }
        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.Контакты CustomAttributes)

        // *** End programmer edit section *** (ЛКС.Контакты CustomAttributes)
        [StrLen(255)]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.Контакты Get start)

                // *** End programmer edit section *** (ЛКС.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (ЛКС.Контакты Get end)

                // *** End programmer edit section *** (ЛКС.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.Контакты Set start)

                // *** End programmer edit section *** (ЛКС.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (ЛКС.Контакты Set end)

                // *** End programmer edit section *** (ЛКС.Контакты Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.Образование CustomAttributes)

        // *** End programmer edit section *** (ЛКС.Образование CustomAttributes)
        [StrLen(255)]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.Образование Get start)

                // *** End programmer edit section *** (ЛКС.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (ЛКС.Образование Get end)

                // *** End programmer edit section *** (ЛКС.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.Образование Set start)

                // *** End programmer edit section *** (ЛКС.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (ЛКС.Образование Set end)

                // *** End programmer edit section *** (ЛКС.Образование Set end)
            }
        }
        
        /// <summary>
        /// Отдел.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.Отдел CustomAttributes)

        // *** End programmer edit section *** (ЛКС.Отдел CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Отдел
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.Отдел Get start)

                // *** End programmer edit section *** (ЛКС.Отдел Get start)
                string result = this.fОтдел;
                // *** Start programmer edit section *** (ЛКС.Отдел Get end)

                // *** End programmer edit section *** (ЛКС.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.Отдел Set start)

                // *** End programmer edit section *** (ЛКС.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (ЛКС.Отдел Set end)

                // *** End programmer edit section *** (ЛКС.Отдел Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (ЛКС.ФИО CustomAttributes)

        // *** End programmer edit section *** (ЛКС.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (ЛКС.ФИО Get start)

                // *** End programmer edit section *** (ЛКС.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (ЛКС.ФИО Get end)

                // *** End programmer edit section *** (ЛКС.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛКС.ФИО Set start)

                // *** End programmer edit section *** (ЛКС.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (ЛКС.ФИО Set end)

                // *** End programmer edit section *** (ЛКС.ФИО Set end)
            }
        }
    }
}
