//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отделы.
    /// </summary>
    // *** Start programmer edit section *** (Отделы CustomAttributes)

    // *** End programmer edit section *** (Отделы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Отделы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Отделы CustomMembers)

        // *** End programmer edit section *** (Отделы CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Отделы.Название CustomAttributes)

        // *** End programmer edit section *** (Отделы.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Отделы.Название Get start)

                // *** End programmer edit section *** (Отделы.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Отделы.Название Get end)

                // *** End programmer edit section *** (Отделы.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отделы.Название Set start)

                // *** End programmer edit section *** (Отделы.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Отделы.Название Set end)

                // *** End programmer edit section *** (Отделы.Название Set end)
            }
        }
    }
}
