//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет_ТЗ.
    /// </summary>
    // *** Start programmer edit section *** (Отчет_ТЗ CustomAttributes)

    // *** End programmer edit section *** (Отчет_ТЗ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Отчет_ТЗ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата_проверки;
        
        // *** Start programmer edit section *** (Отчет_ТЗ CustomMembers)

        // *** End programmer edit section *** (Отчет_ТЗ CustomMembers)

        
        /// <summary>
        /// Дата_проверки.
        /// </summary>
        // *** Start programmer edit section *** (Отчет_ТЗ.Дата_проверки CustomAttributes)

        // *** End programmer edit section *** (Отчет_ТЗ.Дата_проверки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата_проверки
        {
            get
            {
                // *** Start programmer edit section *** (Отчет_ТЗ.Дата_проверки Get start)

                // *** End programmer edit section *** (Отчет_ТЗ.Дата_проверки Get start)
                System.DateTime result = this.fДата_проверки;
                // *** Start programmer edit section *** (Отчет_ТЗ.Дата_проверки Get end)

                // *** End programmer edit section *** (Отчет_ТЗ.Дата_проверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет_ТЗ.Дата_проверки Set start)

                // *** End programmer edit section *** (Отчет_ТЗ.Дата_проверки Set start)
                this.fДата_проверки = value;
                // *** Start programmer edit section *** (Отчет_ТЗ.Дата_проверки Set end)

                // *** End programmer edit section *** (Отчет_ТЗ.Дата_проверки Set end)
            }
        }
    }
}
